:set nowrap
:set expandtab
:set tabstop=2
:set shiftwidth=2
:set number
:set ruler
:syntax on
:set backspace=indent,eol,start
:set cc=121
:set hlsearch
:set incsearch
:hi ColorColumn ctermbg=magenta
au Filetype go set noexpandtab | set tabstop=4 | set shiftwidth=4
au Filetype *sh set noexpandtab | set tabstop=6 | set shiftwidth=6
nnoremap <esc><esc> :noh<CR>
